### ISSUE TITLE
Forms requiring login errors on /submissions

### ISSUE THREAD

**Issue by krispy1298** [gravityforms/gravityformsrestapi#10]
If a form has the setting `Require user to be logged in` checked, the `/submissions` endpoint returns a forbidden state with a response page that is outlined [here](https://codex.wordpress.org/Function_Reference/check_admin_referer#Return).

Found that `check_admin_referer( 'gform_submit_' . $form_id, '_gform_submit_nonce_' . $form_id );` in `gravityforms/form_display.php` stops the submission from going through.

**Comment by spivurno** [comment]
Fixed in: https://github.com/gravityforms/gravityforms/pull/323/commits/e3a039d2a3e1359ef33a0664f3cfdd1b97802a51
