### ISSUE TITLE
Attempting to create form results in missing_title

### ISSUE THREAD

**Issue by khadlock** [gravityforms/gravityformsrestapi#12]
Hi,

Can you please help us troubleshoot why we are receiving a missing_title error? We're posting to the following JSON to the "/forms" endpoint:

```
[{
  "title": "Form Title 1"
},{
  "title": "Form Title 2"
}]
```

And receiving the following error:

```
{
    "code": "missing_title",
    "message": "The form title is missing",
    "data": {
        "status": 400
    }
}
```

Thank you!

**Comment by travislopes** [comment]
It's only possible to create a single form per request.
https://github.com/gravityforms/gravityformsrestapi#post-single-resources

**Comment by khadlock** [comment]
Thanks, I was trying multiple based on old web API. Originally I tried this direction:
```
{
  "title": "Form Title 1"
}
```

Which results in the same error:
```
{
    "code": "missing_title",
    "message": "The form title is missing",
    "data": {
        "status": 400
    }
}
```

**Comment by khadlock** [comment]
In `GF_REST_Forms_Controller` `create_item` if I return the $form immediately after db prepare function I get an object that looks like this:
```
{
    "version": "2.3.2",
    "title": ""
}
```

Code for reference:
```
$form = $this->prepare_item_for_database( $request );
return $form;
```

**Comment by khadlock** [comment]
We discovered that the `prepare_item_for_database` function in "class-controller-forms.php" is causing the issue and have resolved it in our code.

The WP_REST_Request object returns the parameters as a JSON-formatted body when calling `get_json_params`, therefore the following code resolves the issue on lined 381:
`$form = (is_string($form_json)) ? json_decode( $form_json, true ) : $form_json;`

The existing code assumes that $form_json is a string, when it is actually a JSON object. We suggest replacing this line of code with the above or simply assuming it is JSON, since that is what `get_json_params` returns.
https://github.com/gravityforms/gravityformsrestapi/blob/d78afb94c0ff025190a80a74f78e368c848ebdd1/includes/controllers/class-controller-forms.php#L381

**Comment by JeffMatson** [comment]
@khadlock Could you go ahead and make a pull request for this?

Pinging @travislopes for review.

**Comment by khadlock** [comment]
@JeffMatson and @travislopes Pull request has been made: https://github.com/gravityforms/gravityformsrestapi/pull/13

**Comment by acancado** [comment]
This has been resolved. Thanks for the PR @khadlock.
