### ISSUE TITLE
GET /forms is giving me a 401

### ISSUE THREAD

**Issue by hkhuu1011** [gravityforms/gravityformsrestapi#18]
I'm trying to use this endpoint in Postman, and have followed the instructions for OAuth 1.0 and the Basic auth, but it's still giving me a "rest_foridden" status: 401 when I used GET: https://domainname.com/wp-json/gf/v2/forms/167
Is there something I'm missing?
Thanks in advance!

**Comment by antonyjsmith** [comment]
Same here, except OAuth 1.0 works fine

**Comment by stevehenty** [comment]
The REST API v2 is now in Gravity Forms core. Please open a ticket if you still need support.
