### ISSUE TITLE
Errors on Updating Entries

### ISSUE THREAD

**Issue by shannonrl** [gravityforms/gravityformsrestapi#2]
I get the following error when I attempt to update a GF Entry using the REST API.

PUT http://mywebsite.com/wp-json/gf/v2/entries/23

Json Payload: `{"id":"23","form_id":"3","date_created":"2017-01-05 02:05:45","is_starred":0,"is_read":1,"ip":"5.5.5.5","source_url":"http://mywebsite.com/?gf_page=preview&id=3","post_id":null,"currency":"USD","payment_status":null,"payment_date":null,"transaction_id":null,"payment_amount":null,"payment_method":null,"is_fulfilled":null,"created_by":"1","transaction_type":null,"user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36","status":"active","1.3":"fname Update","1.6":"Test Last Name","2":"Test Company","3":"Test Title","4":"Test Message/Notes","5":3,"7":"18","9":"Test DateTime Modified","1.2":"Test Prefix","1.4":"Test Middle Name","1.8":"Test Suffix","10":"shannontest2@email.com","6":"jeff@email.com","8":"2016-12-21T19:23:00Z"}`

Error Message: `Missing entry; Error Code: missing_entry (HTTP Response Status Code: 500)`

I AM using the following Header: `Content-Type: application/json; charset=UTF-8`

I also tried with a smaller JSON Payload, like: `{"1.3":"fname Update","1.6":"Test Last Name"}` which resulted in the same error.

NOTE: I am able to GET and POST Entries without error.

**Comment by zackkatz** [comment]
Have you triple or quadruple-checked to make sure that entry 23 exists and is connected to Form ID 3?

**Comment by shannonrl** [comment]
Yes, even tried it with different entry id: 31

Json payload: `{"id":"31","form_id":"3","date_created":"2017-01-05 09:54:34","is_starred":0,"is_read":1,"ip":"35.163.24.205","source_url":"http://jobrise.com/wp-json/gf/v2/forms/3/entries","post_id":null,"currency":"USD","payment_status":null,"payment_date":null,"transaction_id":null,"payment_amount":null,"payment_method":"","is_fulfilled":null,"created_by":"1","transaction_type":null,"user_agent":"API","status":"active","1.3":"Test First Name","1.4":"Test Middle Name","1.6":"Test Last Name","1.8":"Test Suffix","2":"Test Company","3":"Test Title","4":"Test Message/Notes","5":3,"6":"jeff@recruiterswebsites.com","7":"31","9":"Test DateTime Modified","10":"shannontest3@recruiterswebsites.com","1.2":"Test Prefix"}`

See screenshot of entry via admin page: (trying to update email in this example)
![screenshot 2017-01-06 14 39 44](https://cloud.githubusercontent.com/assets/24931154/21733918/0fdf7c3c-d41e-11e6-9f04-0154145d5b84.png)

I also tried with a smaller json payload for only the fields I am changing and not including the id in the payload, but rather just pointing to the entries endpoint by id: `http://jobrise.com/wp-json/gf/v2/entries/31`

**Comment by shannonrl** [comment]
Just to re-iterate, I am able to GET the entry:

Response JSON:
```json
{
	"id": "31",
	"form_id": "3",
	"date_created": "2017-01-05 09:54:34",
	"is_starred": 0,
	"is_read": 1,
	"ip": "35.163.24.205",
	"source_url": "http:\/\/jobrise.com\/wp-json\/gf\/v2\/forms\/3\/entries",
	"post_id": null,
	"currency": "USD",
	"payment_status": null,
	"payment_date": null,
	"transaction_id": null,
	"payment_amount": null,
	"payment_method": "",
	"is_fulfilled": null,
	"created_by": "1",
	"transaction_type": null,
	"user_agent": "API",
	"status": "active",
	"1.3": "Test First Name",
	"1.4": "Test Middle Name",
	"1.6": "Test Last Name",
	"1.8": "Test Suffix",
	"2": "Test Company",
	"3": "Test Title",
	"4": "Test Message\/Notes",
	"5": "grating5caaa0b36",
	"6": "jeff@recruiterswebsites.com",
	"7": "18",
	"9": "Test DateTime Modified",
	"10": "shannontest2@recruiterswebsites.com",
	"1.2": ""
}
```

**Comment by stevehenty** [comment]
I've not been able to reproduce this I'm afraid. Are you able to update posts successfully? With all other plugins disabled do you get the same error?

**Comment by shannonrl** [comment]
I also tried escaping the quotes in the payload like this:

Single field payload:
`{\"10\": \"shannontest3@recruiterswebsites.com\"}`

All fields payload:
`{\"id\":\"31\",\"form_id\":\"3\",\"date_created\":\"2017-01-05 09:54:34\",\"is_starred\":0,\"is_read\":1,\"ip\":\"35.163.24.205\",\"source_url\":\"http://jobrise.com/wp-json/gf/v2/forms/3/entries\",\"post_id\":null,\"currency\":\"USD\",\"payment_status\":null,\"payment_date\":null,\"transaction_id\":null,\"payment_amount\":null,\"payment_method\":\"\",\"is_fulfilled\":null,\"created_by\":\"1\",\"transaction_type\":null,\"user_agent\":\"API\",\"status\":\"active\",\"1.3\":\"Test First Name\",\"1.4\":\"Test Middle Name\",\"1.6\":\"Test Last Name\",\"1.8\":\"Test Suffix\",\"2\":\"Test Company\",\"3\":\"Test Title\",\"4\":\"Test Message/Notes\",\"5\":3,\"6\":\"jeff@recruiterswebsites.com\",\"7\":\"31\",\"9\":\"Test DateTime Modified\",\"10\":\"shannontest3@recruiterswebsites.com\",\"1.2\":\"Test Prefix\"}`

**Comment by shannonrl** [comment]
oh, did I have to have the base wp-api plugin installed?  I just had the wp-api/basic-auth plugin installed

**Comment by shannonrl** [comment]
I am also using the JSON API - https://wordpress.org/plugins/json-api/

**Comment by stevehenty** [comment]
Assuming you have WP 4.7 installed you don't need to instal the WP REST API plugin to update posts. Does it work if you deactivate the plugin you linked to?

**Comment by shannonrl** [comment]
I am using WP 4.6.1.  Does this make a difference?  Do I need to upgrade to 4.7?

I did try to update a GF Entry with the JSON API deactivated and received the same error.

It doesn't really make sense that the JSON API plugin is causing an issue, however.  Because it is published on a different endpoint (http://example.com/api) vs GF (http://example.com/wp-json/gf/v2).

**Comment by zackkatz** [comment]
Yes, update to 4.7.

**Comment by shannonrl** [comment]
Ok, I updated to version 4.7 and tried again.  Unfortunately, I am still getting the same error.  What should I do next to troubleshoot further?

**Comment by richardW8k** [comment]
Closing. Via HS#168632 issue was identified as a conflict.

**Comment by shannonrl** [comment]
FYI - for anyone else experiencing this issue.  I had a conflict with another plugin: WPJobBoard and I resolved it by using the HTTP verb POST, instead of PUT to perform an update successfully with the WPJobBoard plugin activated.
