### ISSUE TITLE
Input names with periods should be read with underscores

### ISSUE THREAD

**Issue by oxyc** [gravityforms/gravityformsrestapi#3]
PHP automatically converts periods to underscores thus making multiple checkbox input submissions unrecognized. Here's a [discussion with more references](https://github.com/symfony/symfony/issues/9009).

When I post entries that has input fields using `name="6.1"` or similar, the response from the REST API is:

```
1: "single line"
2: ""
3: "Second Choice (default)"
4: "Second Choice"
5: "11"
6_1: "First Choice"
6_3: "Third Choice"
```

Because these field names aren't recognized, they are not recorded in the database either.

**Comment by stevehenty** [comment]
The request and response for the /entries endpoints should both be JSON so the conversion should not happen. Which endpoint are you seeing this on?

**Comment by oxyc** [comment]
Thanks for pointing that out, I was sending it as `multipart/form-data` for uploads but I was using the wrong endpoint. `submissions` what was I needed.

And thanks for a very nice REST API btw, this makes it so much easier to customize the frontend.

**Comment by stevehenty** [comment]
Great - thanks for the feedback, I really appreciate it.
