### ISSUE TITLE
Email notifications are not triggered on POST submission

### ISSUE THREAD

**Issue by ventouris** [gravityforms/gravityformsrestapi#6]
When you create a new form entry with url:

`/wp-json/gf/v2/forms/<form-id>/entries` and method `POST`, the email notifications are not sent even if the entry has been added on the form without an error.

**Comment by richardW8k** [comment]
The entries endpoint is only for adding entries, it does not trigger any of the form submission processes. If you want notifications to be sent you need to use the submissions endpoint: https://www.gravityhelp.com/documentation/article/web-api-v2/#post-forms-form_id-submissions
