### ISSUE TITLE
Required field is triggered even if it should be hidden with conditional logic

### ISSUE THREAD

**Issue by ventouris** [gravityforms/gravityformsrestapi#7]
I have a checkbox on the form with ID 321 and value = "YES".

Then I have 4 other fields with the conditional logic to show if 321 is not YES.

While I send with my HTTP request this `"input_321.1": "YES", "input_321":"YES"`, I receive a response with validation errors on the required fields. The same form works on the website.

Send a POST to URL: `/wp-json/gf/v2/forms/1/submissions`

**Comment by richardW8k** [comment]
For a multiple input field type you need to use the following format for the input name: `input_{field_id}_{input_number}` e.g. `input_321_1`
