### ISSUE TITLE
Form submission is sent directly to trash

### ISSUE THREAD

**Issue by ventouris** [gravityforms/gravityformsrestapi#8]
Trying to send a submission with Postman. I use Basic Authentication with my credentials but the submission goes directly to trash on entries of that form.

URL: /wp-json/gf/v2/forms/1/submissions

I read in the documentation that this happens to avoid spam, but since the HTTP includes user's credentials, it shouldn't be the case.

Edit: Trying with an Administrator user, goes to trash, but with a subscriber user's credentials goes to entries.

**Comment by stevehenty** [comment]
I can't reproduce this I'm afraid. It sounds like Akismet is simply doing its job of learning to mark your test submissions as spam.
