### ISSUE TITLE
GET /entries returns also those from trash

### ISSUE THREAD

**Issue by ventouris** [gravityforms/gravityformsrestapi#9]
When I use the entries path for a specific form, it also returns those entries that are on trash folder.

For example, this is my url:

"/wp-json/gf/v2/forms/1/entries?_labels=1&paging[page_size]=10";

And the return includes also those that have been deleted from the admins.

**Comment by stevehenty** [comment]
Fixed in https://github.com/gravityforms/gravityformsrestapi/commit/d78afb94c0ff025190a80a74f78e368c848ebdd1
